version: "3.9"

services:
  db:
    image: postgres
    container_name: sheets_postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54321:5432"

  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    # ports:
    #   - '8000:8000'
    # environment:
    #   - POSTGRES_DB=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    # depends_on:
    #   - db

      # command:
    #   - /bin/sh
    #   - '-c'
    #   - 'entrypoint.sh
        # command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
